name: Validate lineage yamls

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g ajv-cli
      - name: Validate lineage yamls against schema
        run: bash scripts/validate-lineage-yaml.sh
      - name: Check lineage name in yaml matches file name
        run: bash scripts/validate-file-and-lineage-name.sh
